name: Bug Report TUI
description: Choose this template if you are using (neo)vim in a terminal emulator
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        _Before reporting:_ search [existing issues](https://github.com/sainnhe/sonokai/issues?q=is%3Aissue+is%3Aopen+label%3Abug) and check the FAQ in the help doc. Any bug report which doesn't follow the issue template and I can't reproduce will be closed.

  - type: checkboxes
    attributes:
      label: "I have done the following steps before reporting this issue:"
      options:
      - label: I have searched the existing issues
        required: true
      - label: I have read the FAQ in the help doc
        required: true
  - type: input
    attributes:
      label: "Operating system/version"
      placeholder: "e.g. macOS Big Sur 11.6"
    validations:
      required: true
  - type: input
    attributes:
      label: "Terminal emulator/version"
      placeholder: "e.g. iTerm2 3.4.8"
    validations:
      required: true
  - type: input
    attributes:
      label: "$TERM environment variable"
      placeholder: "Paste the output of `echo $TERM`"
    validations:
      required: true
  - type: input
    attributes:
      label: "Tmux version"
      description: "Fill this section if you are using (neo)vim in tmux."
      placeholder: "Paste the output of `tmux -V`"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Feature matrix"
      description: |
        - If you are using vim, paste **ALL** the output of `vim --version` (execute this command in your terminal emulator)
        - If you are using neovim, paste **ALL** the output of `:checkhealth` (execute this command in your neovim)
        - Triple backticks is the syntax of creating fenced code blocks in markdown, you should paste your output inside the code block.
      placeholder: |
        ```text
        Paste your output here.
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Minimal vimrc that can reproduce this bug."
      placeholder: |
        ```vim
        call plug#begin(fnamemodify(stdpath('data'), ':p') . 'plugins')
        Plug 'sainnhe/sonokai'
        call plug#end()

        set termguicolors
        colorscheme sonokai
        ```
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce this bug using minimal vimrc"
      placeholder: |
        1. Launch neovim using `nvim -u mini.vim`.
        2. Execute `:edit foo.txt`.
        3. Other steps.
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected behavior"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Actual behavior"
    validations:
      required: true
